image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - deploy

deploy_postgres:
  stage: deploy
  image: tiangolo/docker-with-compose
  script:
    - docker-compose -p bot stop
    - docker-compose -p bot rm -f
    - docker-compose -p bot build
    - docker-compose -p bot up -d --remove-orphans
  environment:
    name: Staging
  tags:
    - deploy
    - staging
