image: tiangolo/docker-with-compose

services:
  - docker:19.03.12-dind

stages:
  - deploy

check_dependencies:
  stage: deploy
  image: tiangolo/docker-with-compose
  before_script:
    - docker stop $(docker ps -aq -f ancestor=pdd-tg-bot)
    - docker rm $(docker ps -aq -f ancestor=pdd-tg-bot)
    - docker rmi pdd-tg-bot
    - docker build --build-arg TG_TOKEN=${TG_TOKEN} --build-arg DATABASE_URL=${DATABASE_URL} . -t pdd-tg-bot
  script:
    - docker run pdd-tg-bot
  environment:
    name: Staging
  tags:
    - deploy
    - staging


