version: '3.3'

services:
  db:
    image: postgres:13.4
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_user
      POSTGRES_DB: sample_user
      TZ: GMT+3
    healthcheck:
      test: pg_isready -U sample_user -d sample_user
      interval: 30s
      timeout: 3s
      retries: 3

  redis:
    image: redis:6.2.5
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: redis-cli ping
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data: