version: '3.3'

services:
  bot:
    build:
      context: .
    restart: on-failure
    command: RUN npx tsc && node ./dist/db/fill-db.js && node ./dist/index.js
    environment:
      TG_TOKEN: ${TG_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: ${PORT}
      SECRET_PATH: ${SECRET_PATH}
      DOMAIN: ${DOMAIN}
