version: '3.3'

services:
  bot:
    build:
      context: .
    restart: on-failure
    ports:
      - ${PORT}:80
    environment:
      TG_TOKEN: ${TG_TOKEN}
      DATABASE_URL: ${DATABASE_URL}
      ENVIRONMENT: ${ENVIRONMENT}
      PORT: 80
      SECRET_PATH: ${SECRET_PATH}
      DOMAIN: ${DOMAIN}
    command: ./bot.deploy_commands.sh
  api:
    build:
      context: .
    restart: on-failure
    ports:
      - ${PORT}:80
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: ./api.deploy_commands.sh